WebApplication1/Controllers/CreacionEquiposController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using System.Linq;
using LinqToExcel;
using System.IO;

namespace WebApplication1.Controllers
{
    public class CreacionEquiposController : Controller
    {
        public List<CreacionEquiposModels> ToEntidadHojaExcelList(HttpPostedFileBase pathDelFicheroExcel)
        {
            string archivoruta = @"C:\ArchivosSGR\" + pathDelFicheroExcel.FileName;
            var book = new ExcelQueryFactory(archivoruta);
            var resultado = (from row in book.Worksheet("Hoja1")
                             let item = new CreacionEquiposModels
                             {
                                 Serie = row["SERIE"].Cast<string>(),
                                 Macaddress1 = row["MACADDRESS2"].Cast<string>()
                             }
                             select item).ToList();


            book.Dispose();
            int empresaUsuario = int.Parse(HttpContext.Session["_SessionEmpresa"].ToString());
            ViewData["EmpresaUsuario"] = empresaUsuario;
            return resultado;
        }

        private readonly List<CreacionEquiposModels> clients = new List<CreacionEquiposModels>() 
        { 


        };



        // GET: Client
        public ActionResult Index()
        {
           return View(clients);
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase archivo, string Hoja)
        {
            try
            {
                if (!archivo.Equals(null))
                {
                    
                    return View(ToEntidadHojaExcelList(archivo));
                }

                return View();
            }
            catch (Exception ex)
            {
                return View("Error");
            }
            
        }

        public JsonResult getTipoEquipos(int empresa, TipoModel model)
        {
            List<ListaTiposEquipos> nombreEmpresa = model.listarTipos(empresa);
            return Json(nombreEmpresa, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getBodegaUsuario(int empresa, Bodega model)
        {
            string usuario = "MAUCAM";// HttpContext.Session["_SessionUsuario"].ToString();

            List<ListaBodegaUsuario> BodegaUsuario = model.listarTipos(empresa, usuario);
            return Json(BodegaUsuario, JsonRequestBehavior.AllowGet);
        }


        [AllowAnonymous]
        public ActionResult getMarcaEquipos(Marcas marcas, int idTipo)
        {
            int empresaUsuario = int.Parse(HttpContext.Session["_SessionEmpresa"].ToString());
            HttpContext.Session.Add("_SessionMarcaEquipo", idTipo);

            List<ListaMarcas> nombreBodega = marcas.listarTipos(empresaUsuario, idTipo);

            return Json(nombreBodega, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public ActionResult getModeloEquipos(Modelos modelos, int idTipo)
        {
            int empresaUsuario = int.Parse(HttpContext.Session["_SessionEmpresa"].ToString());
            int idMarca = int.Parse(HttpContext.Session["_SessionMarcaEquipo"].ToString());
            List<ListaModelos> nombreBodega = modelos.listarMarca(empresaUsuario, idTipo, idMarca);



            return Json(nombreBodega, JsonRequestBehavior.AllowGet);
        }

    }
}

WebApplication1/Views/CreacionEquipos/Index.cshtml
@using GridMvc.Html
@{
    ViewBag.Title = "Creación Equipos";
}
@model IEnumerable<WebApplication1.Models.CreacionEquiposModels>
<h2 class="Tituloh2">@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>


<select id="Bodega-lista" name="select"></select>
<select id="Tipo-lista"></select>
<select id="Marca-lista"></select>
<select id="Modelo-lista"></select>

    <hr />
    <label for="archivo">Archivo:</label>

    @using (Html.BeginForm("Index", "CreacionEquipos", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="file" name="archivo" value="browse" />
        <input type="submit" value="Cargar" name="boton" />
        <div class="gridCarga">
            @Html.Grid(Model).AutoGenerateColumns()
        </div>
    }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        @using System.Web.Script.Serialization
    $(document).on("ready", function () {

        $.ajax({
            url: '@Url.Action("getTipoEquipos")' + "?empresa=" + @Html.Encode(ViewData["EmpresaUsuario"]),
            type: "POST",
            success: function (data) {
                var options = "";
                $.each(data, function (index, value) {
                    options += '<option value="' + value.Id + '">' + value.NombreTipoEquipo + '</option>';
                });
                $("#Tipo-lista").html(options);
            },
            error: function () {
                alert("error...");
            }
        });
        
        $.ajax({
            url: '@Url.Action("getBodegaUsuario")' + "?empresa=" + @Html.Encode(ViewData["EmpresaUsuario"]),
            type: "POST",
            success: function (data) {
                var options = "";
                $.each(data, function (index, value) {
                    options += '<option value="' + value.CodAlmacen + '">' + value.NomAlmacen + '</option>';
                });
                $("#Bodega-lista").html(options);
            },
            error: function () {
                alert("error...");
            }
        });

        $.ajax({
            url: '@Url.Action("getEmpresas")' + "?id=" + 1,
                type: "POST",
                success: function (data) {
                    var options = "";
                    $.each(data, function (index, value) {
                        options += '<option value="' + value.Id + '">' + value.NombreEmpresa + '</option>';
                    });
                    $("#segunda-lista").html(options);
                },
                error: function () {
                    alert("error...");
                }
        });

        $("#Tipo-lista").change(function () {
            idSelected = $(this).val();
            $.ajax({
                url: '@Url.Action("getMarcaEquipos")' + "?idTipo=" + idSelected,
                type: "POST",
                success: function (data) {
                    var options = "";
                    $.each(data, function (index, value) {
                        options += '<option value="' + value.IdMarca + '">' + value.NomMarca + '</option>';
                    });
                    $("#Marca-lista").html(options);
                },
                error: function () {
                    alert("error...");
                }
                });
        });

        $("#Marca-lista").change(function () {
            idSelected = $(this).val();
            $.ajax({
                url: '@Url.Action("getModeloEquipos")' + "?idTipo=" + idSelected,
                type: "POST",
                success: function (data) {
                    var options = "";
                    $.each(data, function (index, value) {
                        options += '<option value="' + value.IdModelo + '">' + value.NomModelo + '</option>';
                    });
                    $("#Modelo-lista").html(options);
                },
                error: function () {
                    alert("error...");
                }
            });
        });

        });

        function SetTextBoxValue(){
            var combo = document.getElementById("primera-lista");
            var selected = combo.options[combo.selectedIndex].text;

            var comboEmpresa = document.getElementById("segunda-lista");
            var valorCombo = comboEmpresa.options[comboEmpresa.selectedIndex].text;
            //alert (selected);

            var currentObject = null;
            currentObject = selected;

            $(location).attr('href',"Menu/Menu?valor="+selected+"&valor2="+valorCombo);
        }
    </script>

} 